Cantrip Language: Visitor Class Reference
Visitor Class Reference abstract
Public Member Functions
abstract void visit (Aggregate_Access_Expression e)
abstract void visit (Array_Access_Expression e)
abstract void visit (Binary_Expression e)
abstract void visit (Expression_Statement e)
abstract void visit (Function_Call_Expression e)
abstract void visit (Identifier e)
abstract void visit (If_Statement e)
abstract void visit (Statement_List e)
abstract void visit (Unary_Expression e)
abstract void visit (Value e)
abstract void visit (While_Statement e)
abstract void visit (Builtin_Statement_List e)
Detailed Description
The abstract class representing a Visitor.
The Visitor Pattern is a general programming strategy for handling complex tree structures with heterogeneous node types.
In this case, there is a visit() overload for every possible node type that may appear in the AST. A class inheriting from Visitor must implement all of these overloads. The bodies of the overloads will call child.visit_with(this) in order to call the appropriate visit overload for whatever child type is being visited.
Why have the visit_with function? It's a little ugly to have the exact same code copy-pasted into every single subclass of AST_Node, no? Well, consider that the exact type of a child node may not be known until runtime. For example, the Statement class has a bunch of subclasses for the different types of Statements in Cantrip, and the Interpreter visitor fpr a Statement_List just calls s.visit_with(this) for each statement s in the list, top-to-bottom, trusting that the visit() overload that ultimately gets called will be the right one for whatever particular type of statement s happens to be at runtime.
But, in Java, overload resolution is performed at compile-time. If the Interpreter visit implementation for Statement_List just said visit(s) for each statement in the list, Java would try to find a visit overload in Interpreter for the type Statement at compile time.
If it found one, that's the function that would get called at runtime, which isn't what we want. If it didn't find one, the code would not compile, which also isn't what we want.
What we want is the RUNTIME type of s – not the COMPILE-TIME type of s – to determine which overload of visit() gets called, but that's just not how Java works, so we can't get that. What Java DOES support is subtype polymorphic dynamic dispatch, meaning that we can use the runtime type of a variable to choose which OVERRIDE of a function gets called.
So we use that to get what we want. class AST_Node has an abstract visit_with(Visitor v) method that each non-abstract AST_Node subtype implements in exactly the same way, which is just to call v.visit(this). Since every non-abstract subclass of AST_Node has a visit_with implementation, the static type of this will always be the same as the runtime type of this, so the right overload of visit in the Visitor v will get called.
That's the story, and that's also the story of why this class even exists at all: the visit_with method in AST_Node needs a type to take; that type needs to have visit() overloads for every single non-abstract subclass of AST_Node; and, those methods should be abstract so that we can implement multiple visitors that process or analyze the AST in completely different ways if we want to: remember, not every Visitor will be an interpreter! AST visitors could be compilers, type checkers, or a lot of other things, too.
We exist to be that type.
Definition at line 59 of file Visitor.java.
Member Function Documentation
visit() [1/12]
abstract void Visitor.visit (Aggregate_Access_Expression e) abstract
Reimplemented in Interpreter.
Referenced by Aggregate_Access_Expression.visit_with(), Array_Access_Expression.visit_with(), Binary_Expression.visit_with(), Builtin_Statement_List.visit_with(), Expression_Statement.visit_with(), Function_Call_Expression.visit_with(), Identifier.visit_with(), If_Statement.visit_with(), Statement_List.visit_with(), Unary_Expression.visit_with(), Value.visit_with(), and While_Statement.visit_with().
visit() [2/12]
abstract void Visitor.visit (Array_Access_Expression e) abstract
Reimplemented in Interpreter.
visit() [3/12]
abstract void Visitor.visit (Binary_Expression e) abstract
Reimplemented in Interpreter.
visit() [4/12]
abstract void Visitor.visit (Builtin_Statement_List e) abstract
Reimplemented in Interpreter.
visit() [5/12]
abstract void Visitor.visit (Expression_Statement e) abstract
Reimplemented in Interpreter.
visit() [6/12]
abstract void Visitor.visit (Function_Call_Expression e) abstract
Reimplemented in Interpreter.
visit() [7/12]
abstract void Visitor.visit (Identifier e) abstract
Reimplemented in Interpreter.
visit() [8/12]
abstract void Visitor.visit (If_Statement e) abstract
Reimplemented in Interpreter.
visit() [9/12]
abstract void Visitor.visit (Statement_List e) abstract
Reimplemented in Interpreter.
visit() [10/12]
abstract void Visitor.visit (Unary_Expression e) abstract
Reimplemented in Interpreter.
visit() [11/12]
abstract void Visitor.visit (Value e) abstract
Reimplemented in Interpreter.
visit() [12/12]
abstract void Visitor.visit (While_Statement e) abstract
Reimplemented in Interpreter.
The documentation for this class was generated from the following file:
Visitor.java