Cantrip Language: Interpreter Class Reference
Interpreter Class Reference
Public Member Functions
Interpreter ()
Initialize symbol table only: everything else starts null.
void visit (Aggregate_Access_Expression e)
void visit (Array_Access_Expression e)
void visit (Binary_Expression e)
void visit (Expression_Statement es)
void visit (Function_Call_Expression e)
void visit (Identifier e)
Handle identifier lookup.
void visit (If_Statement is)
void visit (Statement_List sl)
void visit (Unary_Expression ue)
void visit (Value v)
void visit (While_Statement ws)
void visit (Builtin_Statement_List bsl)
Static Public Member Functions
static void error_out (String message)
Private Member Functions
void operator_overload_helper (Value left_hand, Value right_hand, String op)
void handle_assignment (Binary_Expression e)
void process_primitives_operator (Value left, Value right, int op)
Static Private Member Functions
static Value copy_if_literal (Value v)
static int do_operator (int x, int y, int op)
These four redundant methods should be a C macro or C++ template. Java is inadequate.
static double do_operator (int x, double y, int op)
These four redundant methods should be a C macro or C++ template. Java is inadequate.
static double do_operator (double x, int y, int op)
These four redundant methods should be a C macro or C++ template. Java is inadequate.
static double do_operator (double x, double y, int op)
These four redundant methods should be a C macro or C++ template. Java is inadequate.
Private Attributes
ArrayList< TreeMap< String, Value > > symbol_table
The symbol table.
Value cur_value
"Return" values for the visitor methods
Value[] cur_ary
int cur_ary_idx
TreeMap< String, Value > cur_map
only used by idents and ag_access
String cur_str
only used by idents and ag_access
Detailed Description
Definition at line 3 of file Interpreter.java.
Constructor & Destructor Documentation
Interpreter()
Interpreter.Interpreter ()
Initialize symbol table only: everything else starts null.
Definition at line 16 of file Interpreter.java.
          {
               symbol_table = new ArrayList<TreeMap<String,Value>>();
               TreeMap<String,Value> global_symbols = new TreeMap<String,Value>();
               Value v = new Value();
               v.type = Type.FUNCTION;
               v.func_value = new Function();
               v.func_value.formal_parameters = new ArrayList<Parameter>();
               Parameter p = new Parameter();
               p.name = "__BOLVANGAR_BUILTIN_PRINT__";
               p.is_reference = true;
               v.func_value.formal_parameters.add(p);
               v.func_value.body = new Builtin_Statement_List(1);
               global_symbols.put("print",v);
               v = new Value();
               v.type = Type.FUNCTION;
               v.func_value = new Function();
               v.func_value.formal_parameters = new ArrayList<Parameter>();
               v.func_value.body = new Builtin_Statement_List(0);
               global_symbols.put("read_line",v);
               symbol_table.add(global_symbols);
          }
References Function.formal_parameters, Value.func_value, Type.FUNCTION, and symbol_table.
Member Function Documentation
copy_if_literal()
static Value Interpreter.copy_if_literal (Value v) static private
Definition at line 143 of file Interpreter.java.
          {
               Value to_return = v;
               if(v.is_literal)
                    to_return = new Value(v);
               return to_return;
          }
References Value.is_literal.
Referenced by handle_assignment(), and visit().
do_operator() [1/4]
static double Interpreter.do_operator (double x, double y, int op) static private
These four redundant methods should be a C macro or C++ template. Java is inadequate.
Definition at line 547 of file Interpreter.java.
          {
               switch(op)
               {
               case '+': return x+y;
               case '-': return x-y;
               case '*': return x*y;
               case '/': return x/y;
               case '%': return x%y;
               case Cantrip.Lexer.EQUALS: return (x==y ? 1 : 0);
               case Cantrip.Lexer.NOT_EQUALS: return (x!=y ? 1 : 0);
               case '<': return (x<y ? 1 : 0);
               case Cantrip.Lexer.LT_EQUALS: return (x<=y ? 1 : 0);
               case Cantrip.Lexer.GT_EQUALS: return (x>=y ? 1 : 0);
               case '>': return (x>y ? 1 : 0);
               case Cantrip.Lexer.AND: return ((x!=0 && y!=0) ? 1 : 0);
               case Cantrip.Lexer.OR: return ((x!=0 || y!=0) ? 1 : 0);
               default: assert false;
               }
               return -1;
          }
do_operator() [2/4]
static double Interpreter.do_operator (double x, int y, int op) static private
These four redundant methods should be a C macro or C++ template. Java is inadequate.
Definition at line 523 of file Interpreter.java.
          {
               switch(op)
               {
               case '+': return x+y;
               case '-': return x-y;
               case '*': return x*y;
               case '/': return x/y;
               case '%': return x%y;
               case Cantrip.Lexer.EQUALS: return (x==y ? 1 : 0);
               case Cantrip.Lexer.NOT_EQUALS: return (x!=y ? 1 : 0);
               case '<': return (x<y ? 1 : 0);
               case Cantrip.Lexer.LT_EQUALS: return (x<=y ? 1 : 0);
               case Cantrip.Lexer.GT_EQUALS: return (x>=y ? 1 : 0);
               case '>': return (x>y ? 1 : 0);
               case Cantrip.Lexer.AND: return ((x!=0 && y!=0) ? 1 : 0);
               case Cantrip.Lexer.OR: return ((x!=0 || y!=0) ? 1 : 0);
               default: assert false;
               }
               return -1;
          }
do_operator() [3/4]
static double Interpreter.do_operator (int x, double y, int op) static private
These four redundant methods should be a C macro or C++ template. Java is inadequate.
Definition at line 499 of file Interpreter.java.
          {
               switch(op)
               {
               case '+': return x+y;
               case '-': return x-y;
               case '*': return x*y;
               case '/': return x/y;
               case '%': return x%y;
               case Cantrip.Lexer.EQUALS: return (x==y ? 1 : 0);
               case Cantrip.Lexer.NOT_EQUALS: return (x!=y ? 1 : 0);
               case '<': return (x<y ? 1 : 0);
               case Cantrip.Lexer.LT_EQUALS: return (x<=y ? 1 : 0);
               case Cantrip.Lexer.GT_EQUALS: return (x>=y ? 1 : 0);
               case '>': return (x>y ? 1 : 0);
               case Cantrip.Lexer.AND: return ((x!=0 && y!=0) ? 1 : 0);
               case Cantrip.Lexer.OR: return ((x!=0 || y!=0) ? 1 : 0);
               default: assert false;
               }
               return -1;
          }
do_operator() [4/4]
static int Interpreter.do_operator (int x, int y, int op) static private
These four redundant methods should be a C macro or C++ template. Java is inadequate.
Definition at line 475 of file Interpreter.java.
          {
               switch(op)
               {
               case '+': return x+y;
               case '-': return x-y;
               case '*': return x*y;
               case '/': return x/y;
               case '%': return x%y;
               case Cantrip.Lexer.EQUALS: return (x==y ? 1 : 0);
               case Cantrip.Lexer.NOT_EQUALS: return (x!=y ? 1 : 0);
               case '<': return (x<y ? 1 : 0);
               case Cantrip.Lexer.LT_EQUALS: return (x<=y ? 1 : 0);
               case Cantrip.Lexer.GT_EQUALS: return (x>=y ? 1 : 0);
               case '>': return (x>y ? 1 : 0);
               case Cantrip.Lexer.AND: return ((x!=0 && y!=0) ? 1 : 0);
               case Cantrip.Lexer.OR: return ((x!=0 || y!=0) ? 1 : 0);
               default: assert false;
               }
               return -1;
          }
Referenced by process_primitives_operator().
error_out()
static void Interpreter.error_out (String message) static
Definition at line 42 of file Interpreter.java.
          {
               System.err.println(message);
               System.exit(1);
          }
Referenced by handle_assignment(), operator_overload_helper(), and visit().
handle_assignment()
void Interpreter.handle_assignment (Binary_Expression e) private
Handle = and #= operators. They're very special because they are the only operators to update the symbol table. Left hand side should be an lvalue, but we don't check.
Definition at line 154 of file Interpreter.java.
          {
               //For static variables, only do anything first time through
               if(e.is_static && e.is_static_visited)
                    return;
               else if(e.is_static)
                    e.is_static_visited = true;
               //First, evaluate RHS to get value to assign to LHS
               e.right.visit_with(this);
               Value rhs = cur_value;
               //Now, evaluate LHS to get the thing we're assigning to
               e.left.visit_with(this);
               Value lhs = cur_value;
               //It's illegal to assign to a literal (i.e. 3 = 5)
               if(lhs.is_literal)
                    error_out("Attempted to assign to a literal.");
               //For #=, just copy the reference over, unless RHS is literal.
               if(e.operator==Cantrip.Lexer.REF_ASSN)
               {
                    //Error out if LHS invalid
                    if(cur_map==null && cur_ary==null)
                         error_out("Attempted to assign to an r-value.");
                    if(cur_map!=null)
                         cur_map.put(cur_str,(cur_value = copy_if_literal(rhs)));
                    else //cur_ary!=null
                         cur_ary[cur_ary_idx] = (cur_value = copy_if_literal(rhs));
                    cur_str = null;
                    cur_map = null;
               }
               else
                    //For =, if left-hand side is an aggregate, first look for an overload
                    if(lhs.type==Type.AGGREGATE && lhs.ag_value.containsKey("assign"))
                         operator_overload_helper(lhs,rhs,"assign"); //that's it then
                    else //If no overload found or left-hand side isn't an aggregate, invoke clone().
                    {
                         if(cur_map==null && cur_ary==null)
                              error_out("Attempted to assign to an r-value.");
                         //Clone does a one-level-deep copy of the right value and makes it the left value
                         if(cur_map!=null)
                              cur_map.put(cur_str,new Value(rhs));
                         else
                              cur_ary[cur_ary_idx] = new Value(rhs);
                         cur_str = null;
                         cur_map = null;
                         cur_ary = null;
                    }
          }
References Value.ag_value, Type.AGGREGATE, copy_if_literal(), cur_ary, cur_ary_idx, cur_map, cur_str, cur_value, error_out(), Value.is_literal, Binary_Expression.is_static, Binary_Expression.is_static_visited, Binary_Expression.left, Binary_Expression.operator, operator_overload_helper(), Binary_Expression.right, Value.type, and ASTNode.visit_with().
Referenced by visit().
operator_overload_helper()
void Interpreter.operator_overload_helper (Value left_hand, Value right_hand, String op) private
Precondition: left hand is an aggregate Postcondition: cur_value is evaluated operator call
Definition at line 131 of file Interpreter.java.
          {
               if(!left_hand.ag_value.containsKey(op))
                    error_out("Invalid left-hand aggregate for binary expression operator "+op);
               ArrayList<Expression> param_list = new ArrayList<Expression>();
               param_list.add(left_hand);
               param_list.add(right_hand);
               Function_Call_Expression fe = new Function_Call_Expression(left_hand.ag_value.get(op),param_list);
               fe.visit_with(this);
          }
References Value.ag_value, error_out(), and Function_Call_Expression.visit_with().
Referenced by handle_assignment(), and visit().
process_primitives_operator()
void Interpreter.process_primitives_operator (Value left, Value right, int op) private
Definition at line 210 of file Interpreter.java.
          {
               //Create result value and deal with type promotion rules
               Value result = new Value();
               result.type = left.type;
               if(left.type==Type.CHARACTER && right.type!=Type.CHARACTER || //type promotion
                  left.type==Type.INTEGER && right.type==Type.FLOAT)
                    result.type = right.type;
               if(result.type==Type.FLOAT && left.type!=Type.FLOAT)
                    result.float_value = do_operator(left.int_value,right.float_value,op);
               else if(result.type==Type.FLOAT && right.type!=Type.FLOAT)
                    result.float_value = do_operator(left.float_value,right.int_value,op);
               else if(result.type==Type.FLOAT)
                    result.float_value = do_operator(left.float_value,right.float_value,op);
               else
                    result.int_value = do_operator(left.int_value,right.int_value,op);
               //Make sure boolean operators don't evaluate to a float type
               if(op!='+' && op!='-' && op!='*' && op!='/' && op!='%')
                    if(result.type==Type.FLOAT)
                    {
                         result.type = Type.INTEGER;
                         result.int_value = (int)(result.float_value);
                    }
               cur_value = result;
          }
References Type.CHARACTER, cur_value, do_operator(), Type.FLOAT, Value.float_value, Value.int_value, Type.INTEGER, and Value.type.
Referenced by visit().
visit() [1/12]
void Interpreter.visit (Aggregate_Access_Expression e)
Reimplemented from Visitor.
Definition at line 48 of file Interpreter.java.
          {
               //Handle left-hand expression
               e.left.visit_with(this);
               Value left_value = cur_value;
               //If our left-hand expression is neither an aggregate
               //nor an array length call, runtime error.
               if(left_value.type==Type.ARRAY && e.right.equals("length"))
               {
                    cur_value = new Value();
                    cur_value.type = Type.INTEGER;
                    cur_value.int_value = left_value.array_value.length;
                    return;
               }
               else if(left_value.type!=Type.AGGREGATE)
                    error_out("Non-aggregate on left hand side of aggregate access.");
               //The value of our expression is the value of the right-hand side
               cur_value = left_value.ag_value.get(e.right);
               cur_str = e.right;
               cur_map = left_value.ag_value;
               cur_ary = null;
               if(cur_value==null)
               {
                    cur_value = new Value();
                    cur_map.put(cur_str,cur_value);
               }
          }
References Value.ag_value, Type.AGGREGATE, Type.ARRAY, Value.array_value, cur_ary, cur_map, cur_str, cur_value, error_out(), Type.INTEGER, Aggregate_Access_Expression.left, Aggregate_Access_Expression.right, Value.type, and ASTNode.visit_with().
visit() [2/12]
void Interpreter.visit (Array_Access_Expression e)
Reimplemented from Visitor.
Definition at line 78 of file Interpreter.java.
          {
               //If there's no outer expression, that means create a new array
               if(e.outer==null)
               {
                    //Visit the existing inner value expression
                    e.inner.visit_with(this);
                    Value inner_value = cur_value;
                    if(inner_value.type!=Type.INTEGER)
                         error_out("Attempted to create an array with a non-integer argument.");
                    //Do the creation
                    cur_value = new Value();
                    cur_value.type = Type.ARRAY;
                    cur_value.is_literal = true;
                    cur_value.array_value = new Value[inner_value.int_value];
                    //Create each interior element
                    for(int i=0; i<inner_value.int_value; i++)
                         cur_value.array_value[i] = new Value();
                    return;
               }
               //Visit the expression on the left of the []
               e.outer.visit_with(this);
               Value outer_value = cur_value;
               //Visit the expression inside the []
               e.inner.visit_with(this);
               Value inner_value = cur_value;
               //Raw array?
               if(outer_value.type==Type.ARRAY)
               {
                    if(inner_value.type!=Type.INTEGER)
                         error_out("Attempted to access an array with a non-integer.");
                    cur_value = outer_value.array_value[inner_value.int_value];
                    cur_ary = outer_value.array_value;
                    cur_ary_idx = inner_value.int_value;
                    //For arrays, no cur_str or cur_map
                    cur_str = null;
                    cur_map = null;
               }
               else if(outer_value.type==Type.AGGREGATE && outer_value.ag_value.containsKey("index")) //Aggregate implementing index()
                    operator_overload_helper(outer_value,inner_value,"index");
               else
                    error_out("Invalid array access!");
          }
References Value.ag_value, Type.AGGREGATE, Type.ARRAY, Value.array_value, cur_ary, cur_ary_idx, cur_map, cur_str, cur_value, error_out(), Value.int_value, Type.INTEGER, operator_overload_helper(), Value.type, and ASTNode.visit_with().
visit() [3/12]
void Interpreter.visit (Binary_Expression e)
Reimplemented from Visitor.
Definition at line 239 of file Interpreter.java.
          {
               //Special-case assignment and ref-assignment operators
               if(e.operator=='=' || e.operator==Cantrip.Lexer.REF_ASSN)
               {
                    handle_assignment(e);
                    return;
               }
               //Visit left position
               e.left.visit_with(this);
               Value left_value = cur_value;
               //Short-circuit for && and ||
               if(e.operator==Cantrip.Lexer.AND && left_value.int_value==0)
                    return;
               else if(e.operator==Cantrip.Lexer.OR && left_value.int_value!=0)
                    return;
               //Visit right position
               e.right.visit_with(this);
               Value right_value = cur_value;
               //If we're not a number or aggregate, error out
               if(left_value.type!=Type.CHARACTER && left_value.type!=Type.INTEGER &&
                  left_value.type!=Type.FLOAT && left_value.type!=Type.AGGREGATE)
                    error_out("Invalid left-hand side for binary expression operator "+e.operator);
               //Handle operator overloading
               if(left_value.type==Type.AGGREGATE)
               {
                    String op_name = "";
                    switch(e.operator)
                    {
                    case '+': op_name = "add"; break;
                    case '-': op_name = "subtract"; break;
                    case '*': op_name = "multiply"; break;
                    case '/': op_name = "divide"; break;
                    case '%': op_name = "modulo"; break;
                    case Cantrip.Lexer.EQUALS: op_name = "equals"; break;
                    case Cantrip.Lexer.NOT_EQUALS:
                         operator_overload_helper(left_value,right_value,"equals");
                         cur_value.int_value = cur_value.int_value==0 ? 1 : 0;
                         break;
                    case '<': op_name = "lt"; break;
                    case Cantrip.Lexer.LT_EQUALS:
                         operator_overload_helper(left_value,right_value,"lt");
                         if(cur_value.int_value==0)
                              operator_overload_helper(left_value,right_value,"equals");
                         break;
                    case Cantrip.Lexer.GT_EQUALS:
                         operator_overload_helper(left_value,right_value,"lt");
                         cur_value.int_value = cur_value.int_value==0 ? 1 : 0;
                         break;
                    case '>':
                         operator_overload_helper(left_value,right_value,"lt");
                         cur_value.int_value = cur_value.int_value==0 ? 1 : 0;
                         if(cur_value.int_value==1)
{
                              operator_overload_helper(left_value,right_value,"equals");
                              cur_value.int_value = cur_value.int_value==0 ? 1 : 0;
                         }
                         break;
                    default: error_out("Invalid binary operator used with left-hand aggregate.");
                    }
                    operator_overload_helper(left_value,right_value,op_name);
               }
               else
                    process_primitives_operator(left_value,right_value,e.operator);
          }
References Type.AGGREGATE, Type.CHARACTER, cur_value, error_out(), Type.FLOAT, handle_assignment(), Value.int_value, Type.INTEGER, Binary_Expression.left, Binary_Expression.operator, operator_overload_helper(), process_primitives_operator(), Binary_Expression.right, Value.type, and ASTNode.visit_with().
visit() [4/12]
void Interpreter.visit (Builtin_Statement_List bsl)
Reimplemented from Visitor.
Definition at line 434 of file Interpreter.java.
          {
               switch(bsl.stream)
               {
               case 0: String input = bsl.s.nextLine();
                    Value[] values = new Value[input.length()];
                    for(int i=0; i<values.length; i++)
                    {
                         values[i] = new Value();
                         values[i].type = Type.CHARACTER;
                         values[i].int_value = input.charAt(i);
                    }
                    cur_value = new Value();
                    cur_value.type = Type.ARRAY;
                    cur_value.array_value = values;
                    break;
               case 1: (new Identifier("__BOLVANGAR_BUILTIN_PRINT__")).visit_with(this);
                    switch(cur_value.type)
                    {
                    case CHARACTER: System.out.print((char)(cur_value.int_value));
                         break;
                    case INTEGER: System.out.print(cur_value.int_value);
                         break;
                    case FLOAT: System.out.print(cur_value.float_value);
                         break;
                    case ARRAY: for(int i=0; i<cur_value.array_value.length; i++)
                              if(cur_value.array_value[i].type!=Type.CHARACTER)
                                   error_out("Called builtin print with array of something other than characters.");
                              else
                                   System.out.print((char)(cur_value.array_value[i].int_value));
                         break;
                    default: error_out("Called print with invalid value.");
                         break;
                    }
                    break;
               }
          }
References Type.ARRAY, Value.array_value, Type.CHARACTER, cur_value, error_out(), Value.float_value, Value.int_value, Builtin_Statement_List.s, Builtin_Statement_List.stream, and Value.type.
visit() [5/12]
void Interpreter.visit (Expression_Statement es)
Reimplemented from Visitor.
Definition at line 311 of file Interpreter.java.
          {
               es.root_expr.visit_with(this);
          }
References ASTNode.visit_with().
visit() [6/12]
void Interpreter.visit (Function_Call_Expression e)
Reimplemented from Visitor.
Definition at line 316 of file Interpreter.java.
          {
               //Evaluate left-hand side for called function
               e.called_function.visit_with(this);
               //Make sure it's a function, set local var to it
               if(cur_value.type!=Type.FUNCTION)
                    error_out("Tried to call non-function.");
               Function called_function = cur_value.func_value;
               //This will be the new level of the symbol table
               TreeMap<String,Value> new_local_scope = new TreeMap<String,Value>();
               //Reference to formal parameter list, for convenience
               ArrayList<Parameter> formal_parameters = called_function.formal_parameters;
               /*Visit each actual parameter of the function and
                 add it to the new scope with the formal parameter's name.*/
               for(int i=0; i < e.actual_parameters.size(); i++)
               {
                    Parameter fp = formal_parameters.get(i);
                    e.actual_parameters.get(i).visit_with(this);
                    new_local_scope.put(fp.name,fp.is_reference ? copy_if_literal(cur_value) : new Value(cur_value));
               }
               //Add the actual parameter values with the formal parameter names to the new local scope
               symbol_table.add(new_local_scope);
               //Visit the body of the function
               called_function.body.visit_with(this);
               //Pop local scope of returned function
               symbol_table.remove(symbol_table.size()-1);
          }
References Function_Call_Expression.actual_parameters, Function.body, Function_Call_Expression.called_function, copy_if_literal(), cur_value, error_out(), Function.formal_parameters, Value.func_value, Type.FUNCTION, Parameter.is_reference, Parameter.name, symbol_table, Value.type, ASTNode.visit_with(), and Statement_List.visit_with().
visit() [7/12]
void Interpreter.visit (Identifier e)
Handle identifier lookup.
Reimplemented from Visitor.
Definition at line 352 of file Interpreter.java.
          {
               int last_idx = symbol_table.size()-1;
               cur_str = e.name;
               //Current symbol table is last one unless variable exists in global one and also not in last one
               if(symbol_table.get(last_idx).containsKey(cur_str) || !symbol_table.get(0).containsKey(cur_str))
                    cur_map = symbol_table.get(last_idx);
               else
                    cur_map = symbol_table.get(0);
               //If necessary, add a new value to the current symbol table with the name of this identifier
               cur_value = cur_map.get(cur_str);
               if(cur_value==null)
               {
                    cur_value = new Value();
                    cur_map.put(cur_str,cur_value);
               }
          }
References cur_map, cur_str, cur_value, Identifier.name, and symbol_table.
visit() [8/12]
void Interpreter.visit (If_Statement is)
Reimplemented from Visitor.
Definition at line 372 of file Interpreter.java.
          {
               boolean condition = true; //change to false later if needed
               //Evaluate if condition
               is.condition.visit_with(this);
               switch(cur_value.type)
               {
               case CHARACTER: case INTEGER:
                    if(cur_value.int_value==0)
                         condition = false;
                    break;
               case FLOAT:
                    if(cur_value.float_value==0)
                         condition = false;
                    break;
               default:
                    error_out("Invalid if condition expression: not a char/int/float");
                    break;
               }
               if(condition)
                    is.if_branch.visit_with(this);
               else
                    if(is.else_branch!=null)
                         is.else_branch.visit_with(this);
          }
References If_Statement.condition, cur_value, If_Statement.else_branch, error_out(), Value.float_value, If_Statement.if_branch, Value.int_value, Value.type, ASTNode.visit_with(), and Statement_List.visit_with().
visit() [9/12]
void Interpreter.visit (Statement_List sl)
Reimplemented from Visitor.
Definition at line 399 of file Interpreter.java.
          {
               //Unconditional, sequential execution.  Trivial.
               for(Statement s : sl.statements)
                    s.visit_with(this);
          }
References Statement_List.statements, and ASTNode.visit_with().
visit() [10/12]
void Interpreter.visit (Unary_Expression ue)
Reimplemented from Visitor.
Definition at line 406 of file Interpreter.java.
          {
               ue.visit_with(this);
               switch(ue.operator)
               {
               case '-': cur_value.int_value = -cur_value.int_value;
                    cur_value.float_value = -cur_value.float_value;
                    break;
               case '!': cur_value.int_value = cur_value.int_value==0 ? 1 : 0;
                    break;
               }
          }
References cur_value, Value.float_value, Value.int_value, Unary_Expression.operator, and Unary_Expression.visit_with().
visit() [11/12]
void Interpreter.visit (Value v)
Reimplemented from Visitor.
Definition at line 419 of file Interpreter.java.
          {
               cur_value = v;
          }
References cur_value.
visit() [12/12]
void Interpreter.visit (While_Statement ws)
Reimplemented from Visitor.
Definition at line 424 of file Interpreter.java.
          {
               ws.condition.visit_with(this);
               while(cur_value.type==Type.INTEGER && cur_value.int_value!=0)
               {
                    ws.body.visit_with(this);
                    ws.condition.visit_with(this);
               }
          }
References While_Statement.body, While_Statement.condition, cur_value, Value.int_value, Type.INTEGER, Value.type, ASTNode.visit_with(), and Statement_List.visit_with().
Member Data Documentation
cur_ary
Value [] Interpreter.cur_ary private
Definition at line 10 of file Interpreter.java.
Referenced by handle_assignment(), and visit().
cur_ary_idx
int Interpreter.cur_ary_idx private
Definition at line 11 of file Interpreter.java.
Referenced by handle_assignment(), and visit().
cur_map
TreeMap<String,Value> Interpreter.cur_map private
only used by idents and ag_access
Definition at line 12 of file Interpreter.java.
Referenced by handle_assignment(), and visit().
cur_str
String Interpreter.cur_str private
only used by idents and ag_access
Definition at line 13 of file Interpreter.java.
Referenced by handle_assignment(), and visit().
cur_value
Value Interpreter.cur_value private
"Return" values for the visitor methods
primary one
Definition at line 9 of file Interpreter.java.
Referenced by handle_assignment(), process_primitives_operator(), and visit().
symbol_table
ArrayList<TreeMap<String,Value> > Interpreter.symbol_table private
The symbol table.
Definition at line 6 of file Interpreter.java.
Referenced by Interpreter(), and visit().
The documentation for this class was generated from the following file:
Interpreter.java